export enum EnvKey {
  GOOGLE_SERVICE_ACCOUNT = 'GOOGLE_SERVICE_ACCOUNT',
  MONGO_DB_URI = 'MONGO_DB_URI',
  PUB_SUB_PROJECT_ID = 'PUB_SUB_PROJECT_ID',
  PUB_SUB_API_ENDPOINT = 'PUB_SUB_API_ENDPOINT',
  NFTS_EMAIL = 'NFTS_EMAIL',
  PORT = 'PORT',
  STRAPI_JWT_SECRET = 'STRAPI_JWT_SECRET',
}
