version: '3.4'

services:
  api-gateway:
    container_name: 'api-gateway'
    restart: 'always'
    build:
      target: api-gateway
      context: .
      dockerfile: ./Dockerfile.production
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
      - caddy
    ports:
      - '4000:3000'
    env_file: ./env/.api-gateway.env

  user-service:
    container_name: 'user-service'
    restart: 'always'
    build:
      target: user
      context: .
      dockerfile: ./Dockerfile.production
    external_links:
      - pubsub-emulator
    depends_on:
      - pubsub-emulator
      - api-gateway
      - caddy
    ports:
      - '4001:3000'
    env_file: ./env/.user.env

  pubsub-emulator:
    image: knarz/pubsub-emulator
    container_name: 'pubsub-emulator'
    restart: 'always'
    ports:
      - '8085:8085'

  caddy:
    image: caddy:2.3.0-alpine
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/caddy

volumes:
  caddy_data:
  caddy_config:
